# Generated by Rich Lysakowski

import pandas as pd
import streamlit as st
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager

# Read the CSV file
df = pd.read_csv("hackathon_entries.csv")

# Initialize headless browser
options = Options()
options.headless = True
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

# Function to check if a URL loads successfully
def check_url(url):
    try:
        driver.get(url)
        return "Success"
    except Exception as e:
        return "Failure"

# Check each URL and record the result
df["Status"] = df["APP_LINK"].apply(check_url)

# Close the browser
driver.quit()

# Display the results in a Streamlit app
st.title("Streamlit LLM Hackathon App Status")
st.dataframe(df[["APP_NAME", "APP_LINK", "Status"]])